<?xml version='1.0'?>

<robot name="mdu" xmlns:xacro="http://www.ros.org/wiki/xacro" >


  <xacro:property name="main_wheel_length" value="0.05" />
  <xacro:property name="main_wheel_radius" value="0.127" />
  <xacro:property name="main_wheel_weight" value="3.0" />


	
  <xacro:property name="axle_width" value="0.01" /> 
  <xacro:property name="axle_length" value="${0.28}"/> 	
  <xacro:property name="axle_height" value="0.01" /> 						
  <xacro:property name="axle_weight" value="2.0" />

  <xacro:property name="chair_width" value="${axle_length  - 0.05}" /> <!-- From front wheel right joint to front wheel left joint -->
  <xacro:property name="chair_length" value="${chair_width - 0.1}" /> 	 <!-- From front wheel joint to back wheel joint -->
  <xacro:property name="chair_height" value="0.15" /> 				 <!-- From front wheel joint to head rest -->
  <xacro:property name="chair_weight" value="${10.0}" />
  
  <xacro:include filename="$(find mdu_description)/urdf/mdu.gazebo" />
  <xacro:include filename="$(find mdu_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find mdu_description)/urdf/macros.xacro" />

  <link name='footprint'>
    <pose xyz="0 0 0" rpy=" 0 0 0"/>
    <visual>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
    </visual>
    <!--visual>
      <origin xyz="0 0 0" rpy="0 0 -3.14"/>
      <geometry>
         <mesh filename="package://wheelchair_description/meshes/wheelchair_chasis.stl" scale="0.01 0.01 0.01"/>
      </geometry>
  </visual-->
  </link>

  <link name='axle'>
    <inertial>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <mass value="${axle_weight}"/>
      <box_inertia m="${axle_weight}" x="${axle_width}" y="${axle_length}" z ="${axle_height}" />
    </inertial>
    <collision name='collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${axle_width} ${axle_length} ${axle_height}"/>
      </geometry>
    </collision>


    <visual>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${axle_width} ${axle_length} ${axle_height}"/>
      </geometry>
    </visual>
  </link>

  <link name='caster'>
      <collision name='caster_collision'>
	      <origin xyz="0 0 0" rpy=" 0 0 0"/>
	      <geometry>
		<sphere radius="${main_wheel_radius/2}"/>
	      </geometry>
	      <surface>
		<friction>
		  <ode>
		    <mu>0</mu>
		    <mu2>0</mu2>
		    <slip1>1.0</slip1>
		    <slip2>1.0</slip2>
		  </ode>
		</friction>
	      </surface>
    </collision>

    <visual name='caster_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${main_wheel_radius/2}"/>
      </geometry>
   </visual>
 </link>

  <link_joint parent="footprint" child ="axle" xyz="0 0 ${main_wheel_radius}" rpy="0 0 0" type="fixed"/>

  <chassis name="base" xyz="${chair_length/2} 0 0" rpy="0 0 0" m="${chair_weight}" chassisLength="${chair_length}" chassisWidth="${chair_width}" chassisHeight="${chair_height}"/>
  <link_joint parent="axle" child ="base" xyz="0 0 0" rpy="0 0 0" type="fixed"/>
  <link_joint parent="base" child ="caster" xyz="${chair_length -main_wheel_radius/2} 0 ${-main_wheel_radius/2}" rpy="0 0 0" type="fixed"/>
  
  <wheel  lr="rear_left_wheel" tY="0.02" xyz=" 0 0 0" rpy="${-pi/2} 0 0" wheelWidth="${main_wheel_length}" wheelRadius="${main_wheel_radius}" wheelMass="${main_wheel_weight}" meshFile="wheelchair_wheel"/>
  <wheel_joint parent="axle" child ="rear_left_wheel" xyz="0 ${axle_length/2} 0" rpy="0 0 0" axis="0 1 0"/>

  <wheel  lr="rear_right_wheel" tY="0.02" xyz=" 0 0 0" rpy="${pi/2} 0 0" wheelWidth="${main_wheel_length}" wheelRadius="${main_wheel_radius}" wheelMass="${main_wheel_weight}" meshFile="wheelchair_wheel"/>
  <wheel_joint parent="axle" child ="rear_right_wheel" xyz="0 ${-axle_length/2} 0" rpy="0 0 0" axis="0 1 0"/>

 
</robot>
