<?xml version='1.0'?>

<robot name="wheelchair" xmlns:xacro="http://www.ros.org/wiki/xacro" >

  <xacro:property name="cameraSize" value="0.05"/>
  <xacro:property name="cameraMass" value="0.1"/>


  <xacro:property name="legs_width" value="0.01" />
  <xacro:property name="legs_length" value="0.01" />
  <xacro:property name="legs_height" value="0.0354" />
  <xacro:property name="legs_weight" value="2" />

  <xacro:property name="main_wheel_length" value="0.0356884" />
  <xacro:property name="main_wheel_radius" value="0.201784" />
  <xacro:property name="main_wheel_weight" value="3.0" />

  <xacro:property name="small_wheel_radius" value="0.068" />
  <xacro:property name="small_wheel_length" value="0.032" />
  <xacro:property name="small_wheel_weight" value="1.0" />

  <xacro:property name="chair_width" value="${2*main_wheel_radius - 0.2}" /> <!-- From front wheel right joint to front wheel left joint -->
  <xacro:property name="chair_length" value="${3/2*main_wheel_radius}" /> <!-- From front wheel joint to back wheel joint -->
  <xacro:property name="chair_height" value="0.01" /> <!-- From front wheel joint to head rest -->
  <xacro:property name="chair_weight" value="50.0" />



  <xacro:include filename="$(find wheelchair_description)/urdf/wheelchair.gazebo" />
  <xacro:include filename="$(find wheelchair_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find wheelchair_description)/urdf/macros.xacro" />

  <link name='footprint'>
    <visual>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
    <geometry>
      <box size="0.001 0.001 0.001"/>
    </geometry>
    </visual>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 -3.14"/>
      <geometry>
         <mesh filename="package://wheelchair_description/meshes/wheelchair_chasis.stl" scale="0.01 0.01 0.01"/>
      </geometry>
  </visual>
  </link>

  <link name='axel'>
    <inertial>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <mass value="50.0"/>
      <box_inertia m="50" x="0.01" y="0.406054" z ="0.01" />
    </inertial>
    <collision name='collision'>
      <origin xyz="0 0 0}" rpy=" 0 0 0"/>
      <geometry>
        <box size="0.01 0.406054 0.01"/>
      </geometry>
    </collision>


    <visual>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="0.01 0.406054 0.01"/>
      </geometry>
    </visual>
  </link>
  <!--
  <chassis name="base" xyz="0 0 ${main_wheel_radius}" rpy="0 0 0" m="2" chassisLength="0.01" chassisWidth="${2*main_wheel_radius}" chassisHeight="0.01"/>
-->
  <link_joint parent="footprint" child ="axel" xyz="0 0 ${main_wheel_radius}" rpy="0 0 0" type="fixed"/>

  <chassis name="base" xyz="${chair_length/2} 0 0" rpy="0 0 0" m="${chair_weight}" chassisLength="${chair_length}" chassisWidth="${chair_width}" chassisHeight="${chair_height}"/>
  <link_joint parent="axel" child ="base" xyz="0 0 0" rpy="0 0 0" type="fixed"/>

  <chassis name="left_leg" xyz="0 0 ${-legs_height/2}" rpy="0 0 0" m="${legs_weight}" chassisLength="${legs_length}" chassisWidth="${legs_width}" chassisHeight="${legs_height}"/>
  <link_joint parent="base" child ="left_leg" xyz="${chair_length} ${chair_width/2} 0" rpy="0 0 0" type="fixed"/>

  <chassis name="right_leg" xyz="0 0 ${-legs_height/2}" rpy="0 0 0" m="${legs_weight}" chassisLength="${legs_length}" chassisWidth="${legs_width}" chassisHeight="${legs_height}"/>
  <link_joint parent="base" child ="right_leg" xyz="${chair_length} ${-chair_width/2} 0" rpy="0 0 0" type="fixed"/>

  <wheel  lr="l_rev" tY="0.02" xyz=" 0 0 0" rpy="0 0 0" wheelWidth="${main_wheel_length}" wheelRadius="${legs_width}" wheelMass="${legs_weight}" meshFile="wheelchair_wheel_rev"/>
  <wheel_joint parent="left_leg" child ="l_rev" xyz="0 0 ${-legs_height}" rpy="0 0 0" axis="0 0 1"/>
 <!--
  <chassis name="left_leg_b" xyz="0 0 ${-small_wheel_radius}" rpy="0 0 0" m="${legs_weight}" chassisLength="${legs_length}" chassisWidth="${legs_width}" chassisHeight="${2*small_wheel_radius}"/>
  <link_joint parent="l_rev" child ="left_leg_b" xyz="0 0 0" rpy="0 0 0" type="fixed"/>
-->
  <wheel  lr="r_rev" tY="0.02" xyz=" 0 0 0" rpy="0 0 0" wheelWidth="${main_wheel_length}" wheelRadius="${legs_width}" wheelMass="${legs_weight}" meshFile="wheelchair_wheel_rev"/>
  <wheel_joint parent="right_leg" child ="r_rev" xyz="0 0 ${-legs_height}" rpy="0 0 0" axis="0 0 1"/>
<!--
  <chassis name="right_leg_b" xyz="0 0 ${-small_wheel_radius}" rpy="0 0 0" m="${legs_weight}" chassisLength="${legs_length}" chassisWidth="${legs_width}" chassisHeight="${2*small_wheel_radius}"/>
  <link_joint parent="r_rev" child ="right_leg_b" xyz="0 0 0" rpy="0 0 0" type="fixed"/>
-->

  <wheel  lr="l" tY="0.02" xyz=" 0 0 0" rpy="${-pi/2} 0 0" wheelWidth="${main_wheel_length}" wheelRadius="${main_wheel_radius}" wheelMass="${main_wheel_weight}" meshFile="wheelchair_wheel"/>
  <wheel_joint parent="axel" child ="l" xyz="0 ${main_wheel_radius} 0" rpy="0 0 0" axis="0 1 0"/>

  <wheel  lr="r" tY="0.02" xyz=" 0 0 0" rpy="${pi/2} 0 0" wheelWidth="${main_wheel_length}" wheelRadius="${main_wheel_radius}" wheelMass="${main_wheel_weight}" meshFile="wheelchair_wheel"/>
  <wheel_joint parent="axel" child ="r" xyz="0 ${-main_wheel_radius} 0" rpy="0 0 0" axis="0 1 0"/>

  <wheel  lr="lf" tY="0.001" xyz=" 0 0 0" rpy="${pi/2} 0 0" wheelWidth="${small_wheel_length}" wheelRadius="${small_wheel_radius}" wheelMass="${small_wheel_weight}" meshFile="wheelchair_wheel_small"/>
  <wheel_joint parent="l_rev" child ="lf" xyz="0.04 0 ${-2*small_wheel_radius+0.04}" rpy="0 0 0" axis="0 1 0"/>

  <wheel  lr="rf" tY="0.001" xyz=" 0 0 0" rpy="${pi/2} 0 0" wheelWidth="${small_wheel_length}" wheelRadius="${small_wheel_radius}" wheelMass="${small_wheel_weight}" meshFile="wheelchair_wheel_small"/>
  <wheel_joint parent="r_rev" child ="rf" xyz="0.04 0 ${-2*small_wheel_radius + 0.04}" rpy="0 0 0" axis="0 1 0"/>


</robot>
